version: 2.1
executors: 
  node_image: 
    docker:
      - image: cimg/node:14.15

jobs:
  node_test:
    executor: node_image
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          command: |
            yarn install --pure-lockfile
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          command: yarn lint:ci
      - run:
          command: yarn test:ci
  release:
    executor: node_image
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          command: |
            yarn install --pure-lockfile
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          command: yarn semantic-release

workflow:
  build:
    jobs:
      - node_test
      - release:
          requires:
            - node_test
          filters:
            branches:
              only:
                - main