version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.15
      - image: grokzen/redis-cluster
        environment:
          SLAVES_PER_MASTER: 0
    steps:
      - add_ssh_keys:
          fingerprints:
            - 2a:2a:b7:1e:2b:bb:ee:6f:fb:61:36:54:97:69:eb:ee
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          command: |
            yarn install --pure-lockfile
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          command: yarn lint:ci
      - run:
          command: yarn test:ci
      - run:
          command: yarn semantic-release

workflow:
  build:
    jobs:
      - build